### ISSUE TITLE
Image/File upload within grid/form

### ISSUE THREAD

**Issue by rajibulhuda** [pascal-martinez/znetdk4mobile#4]
Hi Pascal,

It is really amazing experience to explore ZnetDK and ZnetDK4Mobile, thank you for your great effort and making this framework opensourced. 

For ZnetDK4Mobile, As in the contact list example if I have an additional field named img and I want to upload image (as file not in db) along with the other fields in the table, moreover I want the  header when the list is viewed in higher resolution screen. How can I achieve this.

Regards
Rajibul.

**Comment by pascal-martinez** [comment]
Hi Rajibul,

To upload an image from the tutorial contact form, you just have to add an `input` element with `type="file"`.
For example: 
```php
<input type="file" name="my_photo">
```

Next, in your App's controller, you save your photo on disk calling the PHP function `move_uploaded_file()`.
The best place where storing your downloaded photo is the App `documents` folder (or within a subfolder, for example `INSTALL_DIR/applications/default/documents/my_photos/`).
See https://mobile.znetdk.fr/settings#z4m-settings-stored-documents to set or get the document folder path.

Finally, to display in a view the uploaded photo, you have to write a `download` action in your app controller.
See https://mobile.znetdk.fr/php-api#z4m-phpapi-controller-setfiletodownload.

To get working examples, here is several links:
- **Code Snippets** - Uploading files from your Application : https://mobile.znetdk.fr/code-snippets/uploading-files-from-your-application
- **Demonstration App** 
    - Live demo at https://mobile.znetdk.fr/demo : from the Demo App, go to menu **Features | Upload** and menu **Features | Download**.
    -  Source code at https://github.com/pascal-martinez/znetdk4mobile-demo

Hoping to have answered your question.
Pascal

**Comment by rajibulhuda** [comment]
![Kazam_screenshot_00016](https://github.com/pascal-martinez/znetdk4mobile/assets/59895817/be9dc59d-273a-47e9-a188-ea5a3d129133)
Hi Pascal,

I tried and followed the steps but unable to make the upload successful!

Thank you.

**Comment by pascal-martinez** [comment]
Hi Rajibul,
Sorry but I can't help you if you don't give me an error message or a faulty behavior of a ZnetDK component compared to the operation that is documented.
Pascal

**Comment by rajibulhuda** [comment]
Thank you very much for your support. I missed move_uploaded_file() function. It is resolved now.
